### ISSUE TITLE
Potential security vulnerability with `marked`

### ISSUE THREAD

**Issue by jedireza** [andris9/nodemailer-markdown#2]
https://nodesecurity.io/advisories/marked_redos

 > ##### Recommendation:
 > As there is no patch available we recommend switching to another markdown parser or if you are able, help out the project by submitting a patch.

[https://github.com/chjj/marked/issues/497](https://github.com/chjj/marked/issues/497#issuecomment-64834128)

 > Try https://github.com/markdown-it/markdown-it , it's much more safe, because of strict parser implementation.

**Comment by andris9** [comment]
I'm aware of the security issue, I hope it gets fixed at one point. Replacing marked with any other markdown parser would require writing a new extension to the renderer that replaces image links, so it's not really straightforward.

**Comment by andris9** [comment]
Thanks, always great to hear that! :blush:
